def graph0(player):
    if player == 0:
        print("                               ")
        print("                               ")
        print("     _______                   ")
        print("    |\      |                  ")
        print("    | \     |                  ")
        print("    |  |    |                  ")
        print("    |  |    |                  ")
        print("    |  |    |                  ")
        print("    |  |    |                  ")
        print("    | o|    |   _\|/^          ")
        print("    |  |    |    (_oo          ")
        print("    |  |    |     |            ")
        print("___ |  |____|____/|\___________")
        print("     \ |          |    _ID     ")
        print("      \|          LL     _ID   ")
        print("                               ")
    else:
        print("                               ")
        print("                               ")
        print("     _______                   ")
        print("    |\      |                  ")
        print("    | \     |                  ")
        print("    |  |    |                  ")
        print("    |  |    |                  ")
        print("    |  |    |                  ")
        print("    |  |    |                  ")
        print("    | o|   _/\|\_\_            ")
        print("    |  | _| .-     \___        ")
        print("    |  | \ /    )     o`o      ")
        print("___ |  | </ ) _/_ )-.___/______")
        print("     \ |/  /\(  (/         _ID ")
        print("      \|| (__`'` '`      _ID   ")
        print("         '--.)                 ")

def graph1(player):
    if player == 0:
        print("                               ")
        print("                               ")
        print("     _______                   ")
        print("    |\      |                  ")
        print("    | \     |                  ")
        print("    |  |    |                  ")
        print("    |  |    |                  ")
        print("    |  |    |                  ")
        print("    |  |    |                  ")
        print("    | o|    |                  ")
        print("    |  |    |                  ")
        print("    |  |    |                  ")
        print("___ |  |____|_______U__U_______")
        print("     \ |   '  '  ` .VD VD '    ")
        print("      \|       '  ` ' . `. `   ")
        print("                               ")
    else:
        print("                               ")
        print("                               ")
        print("     _______                   ")
        print("    |\      |                  ")
        print("    | \     |                  ")
        print("    |  |    |                  ")
        print("    |  |    |                  ")
        print("    |  |    |                  ")
        print("    |  |    |                  ")
        print("    | o|    |                  ")
        print("    |  |    |                  ")
        print("    |  |    |                  ")
        print("___ |  |____|____U__U__U_______")
        print("     \ |   '  '  VD.VD VD '    ")
        print("      \|       U' ` ' . `. `   ")
        print("             ,.VD  .           ")

def graph2(player):
    if player == 0:
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("      T----~~~~~~~--T          ")
        print("______|\     ~~~~~~  \_________")
        print("     \  T-------------T        ")
        print("      \ |             |        ")
        print("       \,,,,,,,,,,,,,,,,       ")
    else:
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("                               ")
        print("_______##############__________")
        print("    ######        ######       ")
        print("       ##############          ")
        print("                               ")

def graph3(player):
    print("                               ")
    print("                               ")
    print("                               ")
    print("                               ")
    print("                               ")
    print("                               ")
    print("                               ")
    print("                               ")
    print("                               ")
    print("                               ")
    print("       _____ooo___U_           ")
    print("      T\  w \_/     \          ")
    print("      | \_|__________\         ")
    print("______|_T____________ T________")
    print("        |             |        ")
    print("        |             |        ")
    print("                               ")
    
def graph4(player):
    print("          ╔╗ ╔╗                ")
    print("          ║║ ║║                ")
    print("╔╗╔╗╔╗╔══╗║║ ║║                ")
    print("║╚╝╚╝║║╔╗║║║ ║║                ")
    print("╚╗╔╗╔╝║║═╣║╚╗║╚╗               ")
    print(" ╚╝╚╝ ╚══╝╚═╝╚═╝               ")
    print("                               ")
    print("  ╔╗                           ")
    print("  ║║                           ")
    print("╔═╝║╔══╗╔═╗ ╔══╗               ")
    print("║╔╗║║╔╗║║╔╗╗║╔╗║               ")
    print("║╚╝║║╚╝║║║║║║║═╣               ")
    print("╚══╝╚══╝╚╝╚╝╚══╝               ")
    print("                               ")
    print("                               ")
    print("                               ")    
def graph5(player):
    print("                               ")
    print("                               ")
    print("╔╗ ╔╗╔══╗╔╗╔╗                  ")
    print("║║ ║║║╔╗║║║║║                  ")
    print("║╚═╝║║╚╝║║╚╝║                  ")
    print("╚═╗╔╝╚══╝╚══╝                  ")
    print("╔═╝║                           ")
    print("╚══╝                           ")
    print("  ╔╗        ╔╗                 ")
    print("  ║║        ║║                 ")
    print("╔═╝║╔╗╔══╗╔═╝║                 ")
    print("║╔╗║╠╣║╔╗║║╔╗║                 ")
    print("║╚╝║║║║║═╣║╚╝║                 ")
    print("╚══╝╚╝╚══╝╚══╝                 ")
    print("                               ")